/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Friendly Captcha Developer Hub",
  "tagline": "Documentation and tutorials to help you get started with Friendly Captcha",
  "favicon": "img/favicon.svg",
  "url": "https://docs.friendlycaptcha.com",
  "baseUrl": "/",
  "organizationName": "friendlycaptcha",
  "projectName": "friendly-docs",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    "docusaurus-plugin-sass"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/tgft/code/work/friendly-docs/sidebars.js",
          "editUrl": "https://github.com/friendlycaptcha/friendly-docs/tree/main/"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/friendlycaptcha/friendly-docs/tree/main/",
          "blogDescription": "Friendly Captcha Engineering Blog",
          "blogTitle": "Friendly Captcha Engineering Blog"
        },
        "theme": {
          "customCss": "/Users/tgft/code/work/friendly-docs/src/css/custom.scss"
        }
      }
    ]
  ],
  "scripts": [
    {
      "src": "https://plausible.io/js/script.js",
      "defer": true,
      "data-domain": "developer.friendlycaptcha.com"
    }
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "image": "img/friendlycaptcha-social-card.jpg",
    "navbar": {
      "title": "",
      "logo": {
        "alt": "Friendly Captcha Developer Hub Logo",
        "src": "img/friendlycaptcha-logo-developer-hub-blue.png",
        "srcDark": "img/friendlycaptcha-logo-developer-hub-blue-dark-mode.png"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "Docs"
        },
        {
          "to": "/docs/integrations/",
          "label": "Integrations",
          "position": "left"
        },
        {
          "to": "/blog",
          "label": "Tech Blog",
          "position": "left"
        },
        {
          "href": "https://docs.friendlycaptcha.com",
          "label": "V1 Docs",
          "position": "right"
        },
        {
          "href": "https://support.friendlycaptcha.com",
          "label": "Support",
          "position": "right"
        },
        {
          "href": "https://app.friendlycaptcha.com/dashboard",
          "label": "Dashboard",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "logo": {
        "alt": "Friendly Captcha Logo",
        "src": "img/friendlycaptcha-logo-white.png",
        "href": "https://friendlycaptcha.com",
        "width": "260px"
      },
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/getting-started/introduction"
            },
            {
              "label": "Guides",
              "to": "/docs/guides/"
            }
          ]
        },
        {
          "title": "Reference",
          "items": [
            {
              "label": "API Reference",
              "to": "/docs/api/overview"
            },
            {
              "label": "SDK Reference",
              "to": "/docs/sdk/reference/"
            }
          ]
        },
        {
          "title": "Links",
          "items": [
            {
              "label": "Dashboard",
              "href": "https://app.friendlycaptcha.eu/dashboard"
            },
            {
              "label": "Status",
              "href": "https://status.friendlycaptcha.com"
            },
            {
              "label": "V1 Documentation",
              "href": "https://docs.friendlycaptcha.com"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/friendlycaptcha"
            },
            {
              "label": "Wordpress Plugin",
              "href": "https://wordpress.org/plugins/friendly-captcha/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2020-2023 | <b>Friendly Captcha GmbH</b>"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
